### ISSUE TITLE
Blank spaces are considered "not empty"

### ISSUE THREAD

**Issue by sachintaksandesiemens** [ianstormtaylor/is-empty#14]
empty("    ") should be true, but returns false instead.

**Comment by nodtem66** [comment]
May be, this issue is like in https://github.com/lodash/lodash/issues/496
`_.isEmpty` is defined by the emptiness of collection, so _.isEmpty(1) -> true
For the definition of this @ianstormtaylor empty function, more discussions are need.

IMHO,
**`if x is empty then x is invalid`** is true,
but **`if x is invalid then x is empty`** is not actually true.
some invalid objects cannot considered as empty, but the empty objects may be considered as invalid.

Is " " an invalid string ? (MAY BE YES)
then, is " " an empty string? (MAY BE NO)

**Comment by sachintaksandesiemens** [comment]
I agree. Thanks for the clarification.
